# -*- coding: utf-8 -*-
"""
Created on 2023-01-28 10:24:23
---------
@summary:
---------
@author: szb
"""

from feapder import Item
from feapder.utils.tools import get_uuid


class InfoListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i info_list 1
    """

    __table_name__ = "info_list"
    
    __unique_key__ = "union_id"

    def __init__(self, *args, **kwargs):
        self.id = kwargs.get('id')  # url md5 128位数值
        self.meta = kwargs.get('meta')  # list页已经解析的一些东西，需要带给detail页的，json格式
        # self.meta_crawl_time = kwargs.get('meta_crawl_time')  # meta 抓取时间
        self.raw = kwargs.get('raw')  # list页item的原始html，以防未来需要处理
        self.release_time = kwargs.get('release_time')  # 发布时间
        self.source = kwargs.get('source')  # 源，用于区分不同源
        # self.state = kwargs.get('state')  # 0:未处理 1:已处理 2:正在处理 -1:处理失败
        self.title = kwargs.get('title')  # 标题
        self.url = kwargs.get('url')  # 链接
        self.union_id = None

    def pre_to_db(self):
        self.id = None
        self.union_id = get_uuid(self.url, self.source)
