# -*- coding: utf-8 -*-
"""
Created on 2023-01-28 11:41:35
---------
@summary:
---------
@author: szb
"""

from feapder import Item


class InfoDetailItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i info_detail 1
    """

    __table_name__ = "info_detail"
    __unique_key__ = "union_id"

    def __init__(self, *args, **kwargs):
        self.union_id = kwargs.get('union_id')  # url md5 128位数值
        self.meta = kwargs.get('meta')  # 其他json数据
        # self.meta_crawl_time = kwargs.get('meta_crawl_time')  # meta 抓取时间
        self.raw = kwargs.get('raw')
        self.source = kwargs.get('source')
        self.url = kwargs.get('url')
