# -*- coding: utf-8 -*-
"""
Created on 2023-04-12 13:45:05
---------
@summary:
---------
@author: user
"""

from feapder import Item


class YgAnhuiInfoListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i yg_anhui_info_list
    """

    __table_name__ = "yg_anhui_info_list"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.union_id = None  # url md5 128位数值
        self.url = None  # 网站链接
        self.title = None  # 标题
        self.release_time = None  # 发布时间
        self.raw = None  # 公示html
        # self.meta_crawl_time = None  # meta 抓取时间
