# -*- coding: utf-8 -*-
"""
Created on 2023-03-31 11:10:43
---------
@summary:
---------
@author: user
"""

from feapder import Item


class YgHainanInfoListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i yg_hainan_info_list
    """

    __table_name__ = "yg_hainan_info_list"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.serial_num = None  # 公式编号
        self.device_name = None  # 产品名称
        self.manufacturer = None  # 生产企业
        self.begin_time = None  # 公示开始时间
        self.end_time = None  # 公示结束时间
        self.state = None  # 状态
        self.raw = None  # list页item的原始数据
        # self.meta_crawl_time = None  # meta 抓取时间
