# -*- coding: utf-8 -*-
"""
Created on 2023-03-30 14:02:02
---------
@summary:
---------
@author: user
"""

from feapder import Item


class YgLiaoningInfoListItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i yg_liaoning_info_list
    """

    __table_name__ = "yg_liaoning_info_list"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.serial_num = None  # 流水号
        self.type = None  # 类别
        self.dir_code = None  # 目录代码
        self.dir_name = None  # 目录名称
        self.device_name = None  # 器械名称
        self.specs = None  # 规格
        self.model = None  # 型号
        self.unit = None  # 单位
        self.manufacturer = None  # 生产企业
        self.bidder = None  # 中标企业
        # self.meta_crawl_time = None  # meta 抓取时间
        self.price = None  # 采购价
